services:

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel
    command: --config /etc/otelcol/config.yaml
    volumes:
      - ./config-otel.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config-prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - observability

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./config-grafana-datasources.yaml:/etc/grafana/provisioning/datasources/provisioning.yml
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - observability

networks:
  observability:
    driver: bridge
