receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317 # gRPC port
      http:
        endpoint: 0.0.0.0:4318 # HTTP port

exporters:
  prometheus:
    endpoint: otel-collector:8889
  otlphttp/logs:
    endpoint: loki:3100/otlp
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      exporters: [otlphttp/logs]
